--- Question 1 ---
SELECT * FROM DICT;
SELECT COUNT(*) FROM DICT; /*1821*/
DESC DICT;

--- Question 2 ---
DESC ALL_TAB_COLUMNS;
SELECT * FROM ALL_TAB_COLUMNS;
-- Le rôle c'est d'afficher les informations sur tous les attributs des tables de tous les utilisateurs --
DESC USER_USERS;
SELECT * FROM USER_USERS;
-- Le rôle c'est d'afficher toutes les informations du compte connecté --
DESC ALL_CONSTRAINTS;
SELECT * FROM ALL_CONSTRAINTS;
-- Le rôle c'est d'afficher toutes les contraintes des utilisateurs --
DESC USER_TAB_PRIVS;
SELECT * FROM USER_TAB_PRIVS;
-- Le rôle c'est d'afficher les droits d'acces des tables de l'utilisateurs qui ont été grantéé pour d'autres users --

--- Question 3 ---
SELECT USERNAME FROM USER_USERS;

--- Question 4 ---
DESC  ALL_TAB_COLUMNS;
SELECT * FROM ALL_TAB_COLUMNS;
SELECT COUNT(*) FROM ALL_TAB_COLUMNS; /*45667*/
DESC USER_TAB_COLUMNS;
SELECT * FROM USER_TAB_COLUMNS;
SELECT COUNT(*) FROM USER_TAB_COLUMNS; /*1439*/
SELECT COUNT(*) FROM ALL_TAB_COLUMNS WHERE OWNER=(SELECT USERNAME FROM USER_USERS); /*1439*/
-- La différence c'est ALL_TAB_COLUMNS contient toutes les informations sur les tables de tous les utilisateurs --
-- Mais USER_TAB_COLUMNS contient sauf les informations dur les tables de l'utilisateur connect --


--- Question 5 ---
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='DBAHOPITAL';
SELECT TABLE_NAME,TABLESPACE_NAME,SAMPLE_SIZE FROM ALL_TABLES WHERE OWNER='DBAHOPITAL';

--- Question 6 ---
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='SYSTEM';
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='DBAHOPITAL';

--- Question 7 --- (Connecté en tant que DBAHOPITAL)
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='PATIENT';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='HOSPITALISATION';

--- Question 8 ---
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='HOSPITALISATION' AND CONSTRAINT_TYPE='R';


--- Question 9 ---
SELECT * FROM USER_CONSTRAINTS;
-- Le propriétaire, nom, type, table, propiétaire de la table référencé


--- Question 10 ---
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME='HOSPITALISATION';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='HOSPITALISATION';
SELECT * FROM USER_INDEXES WHERE TBALE_NAME='HOSPITALISATION';

--- Question 11 --- (Connecté avec AdminHopital)
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM SESSION_PRIVS;

--- Question 12 ---
SELECT * FROM SESSION_ROLES;

--- Question 13 ---
SELECT * FROM USER_OBJECTS;

--- Question 14 ---
SELECT OWNER FROM ALL_TABLES where TABLE_NAME='HOSPITALISATION';

--- Question 15 ---(Connecté DBAHOPITAL)
SELECT BYTES/1024 AS TAILLE_EN_KO FROM USER_EXTENTS WHERE SEGMENT_NAME='HOSPITALISATION';

--- Question 16 ---(Connecté System)
SELECT TABLESPACE_NAME,BLOCK_SIZE,CONTENTS,LOGGING FROM DBA_TABLESPACES WHERE TABLESPACE_NAME LIKE 'HOSPITAL%';
SELECT * FROM ALL_USERS WHERE USERNAME='DBAHOPITAL';
SELECT GRANTEE,OWNER,TABLE_NAME,PRIVILEGE,GRANTABLE FROM USER_TAB_PRIVS;